AllCops:
  TargetRubyVersion: '2.5'

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  Enabled: false

Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Metrics/MethodLength:
  Max: 20
